## numpy is a multi dimentional array.

## numpy is faster than list because it is using fixed dtypes

### normal python variable declaration -> in memory how will it get created.
    1. size -> 4 bytes.
    2. refrence count -> 8 bytes.
    3.object type -> 8 bytes.
    4.object value -> 8 bytes.

#### this is why python( dynamic language) consuming more memory than a statically types language!

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
# get dimention
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# get shape
a.shape

(3,)

In [7]:
b.shape

(2, 5)

In [8]:
# get type

In [9]:
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('int64')

In [11]:
# get size --> in bytes
a.itemsize

2

In [12]:
b.itemsize

8

In [13]:
# get total size
a.size * a.itemsize

6

In [14]:
a.nbytes

6

In [15]:
b.nbytes

80

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
a.shape # get shape

(2, 7)

In [18]:
# get a specific elem [row, column]
a[0,-2]

np.int64(6)

In [19]:
# get a specific row
a[:, 2]

array([ 3, 10])

In [20]:
a[1:3, 4:7]

array([[12, 13, 14]])

In [21]:
a[:, 4:7]

array([[ 5,  6,  7],
       [12, 13, 14]])

In [22]:
a[:, 2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 13, 14]])

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
b.shape

(2, 2, 2)

In [25]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [63]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [69]:
np.ones((4,3), dtype='i1')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)